
import java.util.Random;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Extreme pc
 */
public class Matrices extends javax.swing.JFrame {

    /**
     * Creates new form Matrices
     */
    public Matrices() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbltitulo1 = new javax.swing.JLabel();
        lbltitulo2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        btngenerar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtmatriz1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtmatriz2 = new javax.swing.JTextArea();
        btnlimpiar2 = new javax.swing.JButton();
        btnlimpiar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        lbltitulo1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbltitulo1.setText("Matriz 1");

        lbltitulo2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lbltitulo2.setText("Matriz 2");

        btngenerar.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        btngenerar.setText("Generar");
        btngenerar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btngenerarMouseClicked(evt);
            }
        });
        btngenerar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btngenerarKeyPressed(evt);
            }
        });

        txtmatriz1.setEditable(false);
        txtmatriz1.setColumns(20);
        txtmatriz1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmatriz1.setRows(5);
        txtmatriz1.setAutoscrolls(false);
        jScrollPane1.setViewportView(txtmatriz1);

        txtmatriz2.setEditable(false);
        txtmatriz2.setColumns(20);
        txtmatriz2.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        txtmatriz2.setRows(5);
        txtmatriz2.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtmatriz2);

        btnlimpiar2.setText("Limpiar");
        btnlimpiar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiar2ActionPerformed(evt);
            }
        });

        btnlimpiar1.setText("Limpiar");
        btnlimpiar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlimpiar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnlimpiar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btngenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(193, 193, 193)
                                .addComponent(btnlimpiar2)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbltitulo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lbltitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(350, 350, 350))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(234, 234, 234))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(232, 232, 232))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbltitulo1)
                .addGap(41, 41, 41)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbltitulo2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(btngenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnlimpiar2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnlimpiar1, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btngenerarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btngenerarMouseClicked
        Random ra = new Random();
        String[][] matriz = new String[5][5];
        for (int i = 0; i < 5; i++) {
            matriz[i][0] = String.valueOf(ra.nextInt(50) + 1);
            for (int k = 1; k < 5; k++) {
                matriz[i][k] = String.valueOf(ra.nextInt(50) + 1);
            }
        }
        for (int i = 0; i < 5; i++) {
            txtmatriz1.setText(txtmatriz1.getText() + matriz[i][0] + " ");
            for (int k = 1; k < 5; k++) {
                txtmatriz1.setText(txtmatriz1.getText() + matriz[i][k] + " ");
            }
            txtmatriz1.setText(txtmatriz1.getText() + System.lineSeparator());
        }
        for (int i = 0; i < 5; i++) {
            if ((Integer.parseInt(matriz[i][0]) % 2) == 0) {
                matriz[i][0] = "$";
            } else {
                matriz[i][0] = "#";
            }
            for (int k = 1; k < 5; k++) {
                if ((Integer.parseInt(matriz[i][k]) % 2) == 0) {
                    matriz[i][k] = "$";
                } else {
                    matriz[i][k] = "#";
                }
            }
        }
        for (int i = 0; i < 5; i++) {
            txtmatriz2.setText(txtmatriz2.getText() + matriz[i][0] + " ");
            for (int k = 1; k < 5; k++) {
                txtmatriz2.setText(txtmatriz2.getText() + matriz[i][k] + " ");
            }
            txtmatriz2.setText(txtmatriz2.getText() + System.lineSeparator());
        }
    }//GEN-LAST:event_btngenerarMouseClicked

    private void btngenerarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btngenerarKeyPressed

    }//GEN-LAST:event_btngenerarKeyPressed

    private void btnlimpiar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiar2ActionPerformed
        txtmatriz1.setText("");
        txtmatriz2.setText("");
    }//GEN-LAST:event_btnlimpiar2ActionPerformed

    private void btnlimpiar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlimpiar1ActionPerformed
        txtmatriz1.setText("");
        txtmatriz2.setText("");
    }//GEN-LAST:event_btnlimpiar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Matrices.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Matrices().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btngenerar;
    private javax.swing.JButton btnlimpiar1;
    private javax.swing.JButton btnlimpiar2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbltitulo1;
    private javax.swing.JLabel lbltitulo2;
    private javax.swing.JTextArea txtmatriz1;
    private javax.swing.JTextArea txtmatriz2;
    // End of variables declaration//GEN-END:variables
}
